AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
