AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'lib/local_https/proxy.rb'
    - 'lib/local_https/cli.rb'
    - 'lib/local_https/cert_manager.rb'
Metrics/AbcSize:
  Exclude:
    - 'lib/local_https/proxy.rb'
    - 'lib/local_https/cli.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/local_https/proxy.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/local_https/proxy.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/local_https/proxy.rb'
